---

- name: download minio server
  shell: "wget -O {{ minio_server_bin }} {{ minio_server_download_url }}"

- name: chown minio server
  shell: "chown {{ minio_user }}:{{ minio_group }} {{ minio_server_bin }}"

- name: chmod minio server
  shell: "chmod 0755 {{ minio_server_bin }}"

- name: generate the minio server envfile
  template:
    src: minio.env.j2
    dest: "{{ minio_server_envfile }}"
  notify: restart minio

- name: create the minio server systemd config
  template:
    src: minio.service.j2
    dest: "{{ systemd_units_dir }}/minio.service"
  when: ansible_service_mgr == "systemd"

- name: create the minio server init.d config
  template:
    src: minio.init.j2
    dest: "{{ initd_conf_dir }}/minio"
    mode: 0755
  when: ansible_service_mgr != "systemd"

- name: create the minio server main config
  template:
    src: minio.conf.j2
    dest: "/etc/init/minio.conf"
  notify: restart minio

- name: enable and start the minio service
  service:
    name: minio
    state: started
    enabled: yes
